# Generated by Django 2.1.7 on 2019-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190324_1506'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observed',
            field=models.ManyToManyField(blank=True, to='Store.Book'),
        ),
    ]
